#!/usr/bin/env python3
import csv

OUT = "/tmp/mongle-wave6-0ab/6.0A/asset_manifest.csv"

rows = [
 dict(asset_path="uploads/family_platform_pin_logo_transparent_1024.png", format="PNG", dimension="1024x1024",
   transparent="yes(RGBA)", source_screen="A1,A1-S1,A2,A3,A4,A5(로고 워터마크/브랜드 아이콘으로 반복 사용, 총 6+회 img src 참조)",
   usage="브랜드 마스코트(핀 모양 캐릭터, confetti 포함) — 히어로 로고, 서비스 그리드 아이콘, 헤더 아이콘 등 다목적",
   master_candidate="YES(가장 큰 해상도, 명시적 'master' 파일명은 아니나 유일한 1024px 브랜드 캐릭터 원본)",
   variant="다른 크기(96/130/150/210px 등)는 이 파일을 object-fit:contain으로 축소 사용, 별도 파일 없음",
   light_dark="라이트 배경 전용 확인됨(투명배경이라 다크 대응 가능성 있으나 별도 dark variant 파일 없음, NOT_VERIFIED)",
   scaling_quality="1024px 원본이라 96~210px 축소 사용에는 충분, 다만 admin 사이드바 130px 표시 시 좌우 여백(confetti) 포함되어 실제 로고 대비 작아 보임(TIER1 참조)",
   missing_source="없음(원본 확보됨)", duplicate="brand_pin_logo_transparent.png(2048x2048)과 동일 컨셉의 다른 해상도 — 완전 동일 파일인지는 SHA 다름으로 별도 파일 확인(DUPLICATE_CONCEPT, NOT_BYTE_DUPLICATE)",
   implementation_suitability="적합(투명 배경, 고해상도)", licensing="NOT_VERIFIED(생성 AI 산출물로 추정되나 출처 라이선스 명시 없음)"),
 dict(asset_path="uploads/brand_pin_logo_transparent.png", format="PNG", dimension="2048x2048",
   transparent="yes(RGBA)", source_screen="승인 10개 화면 어디에서도 직접 src 참조 관측 안됨(html grep 결과 미포함)",
   usage="미사용 원본(더 큰 해상도 브랜드 자산, HTML에서 미참조)",
   master_candidate="YES(최고해상도 후보, 그러나 실제 사용처가 HTML에 없어 ASSET_MASTER_CANDIDATE이지 확정 사용본 아님)",
   variant="family_platform_pin_logo_transparent_1024.png와 동일 컨셉의 상위 해상도", light_dark="NOT_VERIFIED",
   scaling_quality="2048px로 향후 대형 사용(예: 스플래시)에 적합", missing_source="없음",
   duplicate="1024px 버전과 컨셉 중복(DUPLICATE_CONCEPT)",
   implementation_suitability="적합(마스터 원본 후보)", licensing="NOT_VERIFIED"),
 dict(asset_path="uploads/family_platform_style_guide_v1.png", format="PNG", dimension="1600x6773",
   transparent="no(RGB)", source_screen="HTML에서 미참조(독립 스타일가이드 문서 이미지)",
   usage="SHARED_STYLE_REFERENCE — 컴포넌트/컬러/타이포 언어 확인용 세로 롱 이미지",
   master_candidate="NO", variant="family_platform_style_guide_preview.png(1600x4400)가 축약판으로 추정",
   light_dark="NOT_VERIFIED", scaling_quality="N/A(참조용, 구현에 직접 사용 안 함)",
   missing_source="없음", duplicate="preview 버전과 내용 중복 가능성(다른 높이) — 바이트 동일 아님(별도 SHA)",
   implementation_suitability="구현 자산 아님(참조 문서)", licensing="NOT_VERIFIED"),
 dict(asset_path="uploads/family_platform_style_guide_preview.png", format="PNG", dimension="1600x4400",
   transparent="no(RGB)", source_screen="HTML에서 미참조", usage="SHARED_STYLE_REFERENCE(축약 프리뷰)",
   master_candidate="NO", variant="v1의 축약본으로 추정(NOT_VERIFIED)", light_dark="NOT_VERIFIED",
   scaling_quality="N/A", missing_source="없음", duplicate="v1과 내용 중복 가능성",
   implementation_suitability="구현 자산 아님(참조 문서)", licensing="NOT_VERIFIED"),
 dict(asset_path="uploads/screen_login_approved.png", format="PNG", dimension="853x1844",
   transparent="no(RGB)", source_screen="A1(1:1 대응, PRIMARY_VISUAL_SOURCE)",
   usage="A1 최종 렌더링 검증 기준", master_candidate="NO(스크린샷, 마스터 자산 아님)",
   variant="A1-S1(순수 로그인)의 전용 PNG 없음(SOURCE_MISSING)", light_dark="라이트 테마만 확인",
   scaling_quality="고해상도 스크린샷, 품질 이슈 없음", missing_source="A1-S1 전용본 없음",
   duplicate="없음", implementation_suitability="시각 검증 기준으로 적합", licensing="NOT_VERIFIED"),
 dict(asset_path="uploads/screen_family_home_approved.png", format="PNG", dimension="941x1672",
   transparent="no(RGB)", source_screen="A2(1:1 대응)", usage="A2 최종 렌더링 검증 기준",
   master_candidate="NO", variant="없음", light_dark="라이트 테마만", scaling_quality="양호",
   missing_source="없음", duplicate="없음", implementation_suitability="적합", licensing="NOT_VERIFIED"),
 dict(asset_path="uploads/screen_point_festival_approved.png", format="PNG", dimension="941x1672",
   transparent="no(RGB)", source_screen="A3(1:1 대응)", usage="A3 최종 렌더링 검증 기준",
   master_candidate="NO", variant="없음", light_dark="라이트 테마만", scaling_quality="양호",
   missing_source="없음", duplicate="없음", implementation_suitability="적합", licensing="NOT_VERIFIED"),
 dict(asset_path="uploads/screen_family_chat_approved.png", format="PNG", dimension="941x1672",
   transparent="no(RGB)", source_screen="A4(1:1 대응, 단 Room List 미포함)", usage="A4 최종 렌더링 검증 기준(단일 GROUP 룸 진입 상태만)",
   master_candidate="NO", variant="Room List, DIRECT/SERVICE 룸 전용 PNG 없음(APPROVED_SOURCE_GAP)", light_dark="라이트 테마만",
   scaling_quality="양호", missing_source="Room List/DIRECT/SERVICE 화면 PNG 없음", duplicate="없음",
   implementation_suitability="A4 conversation 뷰에 한해 적합", licensing="NOT_VERIFIED"),
 dict(asset_path="uploads/screen_admin_point_approved.png", format="PNG", dimension="1448x1086",
   transparent="no(RGB)", source_screen="A5(1:1 대응, TIER1 최고 일치도)", usage="A5 최종 렌더링 검증 기준",
   master_candidate="NO", variant="다른 사이드바 5개 화면(대시보드/미션관리/사용자관리/알림관리/설정) 전용 PNG 없음(APPROVED_SOURCE_GAP)",
   light_dark="라이트 테마만", scaling_quality="양호", missing_source="사이드바 나머지 5개 화면 PNG 없음",
   duplicate="없음", implementation_suitability="적합(A5 한정)", licensing="NOT_VERIFIED"),
 dict(asset_path="uploads/19de6297-c168-45f4-be59-878a01bc0641.png", format="PNG", dimension="1536x1024",
   transparent="no(RGB)", source_screen="HTML에서 미참조, 파일명이 UUID라 용도 불명",
   usage="UNKNOWN(파일명만으로 용도 추정 불가)", master_candidate="NO",
   variant="NOT_VERIFIED", light_dark="NOT_VERIFIED", scaling_quality="NOT_VERIFIED",
   missing_source="N/A", duplicate="NOT_VERIFIED", implementation_suitability="UNKNOWN — 육안 확인 권장(PM Gate)",
   licensing="NOT_VERIFIED"),
 dict(asset_path="(inline) 24x24 outline SVG icon set", format="inline <svg> (HTML 내 literal, 파일 아님)",
   dimension="21-23px 표시 크기, viewBox 24x24", transparent="n/a(vector)",
   source_screen="A2,A3,A4,A5,EXTRA(BottomDock 4종: 홈/포인트잔치/대화/나, AdminSidebar 6종, EXTRA-01 설정류 아이콘 등 총 9종 이상 확인)",
   usage="네비게이션 아이콘(outline style, stroke-width 1.8, round cap/join)",
   master_candidate="NO(파일 아님, 인라인 코드)", variant="stroke color만 active/inactive로 변형(#5A35DF vs #A8A5B6)",
   light_dark="stroke 색상 하드코드(다크테마 별도 대응 없음)", scaling_quality="벡터라 스케일 이슈 없음",
   missing_source="아이콘 세트가 별도 SVG 스프라이트/아이콘 폰트 파일로 분리되어 있지 않음 — 현재 구현에서 재사용하려면 코드에서 직접 추출 필요",
   duplicate="화면 간 동일 path 데이터 반복(홈/포인트잔치/대화 아이콘은 4개 화면에서 완전 동일 path 재사용 확인)",
   implementation_suitability="적합(벡터, 추출 가능)", licensing="NOT_VERIFIED(자체 제작 추정)"),
 dict(asset_path="(inline) emoji glyphs", format="유니코드 이모지(폰트 렌더링, 에셋 파일 아님)",
   dimension="font-size 기반(9-20px)", transparent="n/a",
   source_screen="A2(🔔💜🎉),A3(🧹📖👥💳),A4(📎📷🖼✨👍😊🍚),EXTRA(🗓️🖼️📋 등)",
   usage="장식/의미 전달용 이모지(시스템 폰트 렌더링에 의존)", master_candidate="NO",
   variant="플랫폼별 렌더링 상이(OS 이모지 폰트 의존 — 크로스플랫폼 일관성 NOT_VERIFIED)",
   light_dark="n/a", scaling_quality="시스템 의존적", missing_source="n/a",
   duplicate="n/a", implementation_suitability="주의 필요(EMOJI_PLACEHOLDER 성격 — 실제 아이콘 자산으로 교체 검토 대상일 수 있음, PM_DECISION_REQUIRED)",
   licensing="n/a(시스템 폰트)"),
 dict(asset_path="(inline) fake iOS status bar", format="CSS 도형 조합(div/i 요소, 파일 아님)",
   dimension="10개 화면 전체 상단 반복", transparent="n/a",
   source_screen="ALL(A1,A1-S1,A2,A3,A4,EXTRA — 모바일 10종 전체)",
   usage="OS chrome 모방(9:41 시각, 신호/와이파이/배터리 아이콘)",
   master_candidate="NO", variant="없음(전 화면 동일)", light_dark="다크 텍스트 고정(#17103A)",
   scaling_quality="n/a", missing_source="n/a", duplicate="10회 완전 동일 반복",
   implementation_suitability="PRESENTATION_ARTIFACT — 운영 UI에 그대로 넣으면 안 되는 디자인 캔버스 전용 목업 장식(실제 브라우저/PWA는 실기기 상태바를 별도로 가짐)",
   licensing="n/a"),
 dict(asset_path="(inline) phone mockup frame + home indicator bar", format="CSS(div, 파일 아님)",
   dimension="480px 폭 프레임 + 132x5px 하단 바", transparent="n/a",
   source_screen="ALL(모바일 10종)", usage="디바이스 프레임 모방",
   master_candidate="NO", variant="없음", light_dark="n/a", scaling_quality="n/a",
   missing_source="n/a", duplicate="10회 반복", implementation_suitability="PRESENTATION_ARTIFACT — 실제 구현에 포함하지 않을 디자인 캔버스 장식(홈 인디케이터 바는 실기기가 자체 표시)",
   licensing="n/a"),
 dict(asset_path="(inline) photo attachment placeholder texture", format="CSS repeating-linear-gradient(파일 아님)",
   dimension="74x74px x3", transparent="no", source_screen="A4(사진 3장 첨부 예시)",
   usage="실제 사진 대신 사용된 회색 대각선 텍스처 + '사진 1/2/3' 텍스트",
   master_candidate="NO", variant="없음", light_dark="n/a", scaling_quality="n/a",
   missing_source="실제 사진 자산 없음(의도적 placeholder)",
   duplicate="3회 동일 패턴", implementation_suitability="LOW_RESOLUTION_PLACEHOLDER — 실제 앨범/사진 렌더링 방식은 이 목업만으로 확정 불가(PM_DECISION_REQUIRED)",
   licensing="n/a"),
]

fieldnames = ["asset_path","format","dimension","transparent","source_screen","usage","master_candidate",
  "variant","light_dark","scaling_quality","missing_source","duplicate","implementation_suitability","licensing"]

with open(OUT, "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=fieldnames)
    w.writeheader()
    for r in rows:
        w.writerow(r)
print(f"wrote {len(rows)} rows")
