#!/usr/bin/env python3
import csv
OUT = "/tmp/mongle-wave6-0ab/6.0B/current_screen_route_map.csv"

rows = [
 dict(route="/", route_definition='App.tsx line 56-63: <Route path="/" element={<AuthPage/>}/>', page_component="pages/Auth/index.tsx",
   layout_shell="없음(Shell 밖, data-domain=user wrapper만)", auth_requirement="비로그인 전용(로그인 시 /dashboard 또는 /admin으로 Navigate)",
   family_context_requirement="없음", service_subscription_requirement="없음", data_source="GET /api/players(fixture 아님, 실제 API)",
   loading_empty_error="PlayerSelectView 내부에서 처리(구체 상태 NOT_VERIFIED, 코드 미상세열람)",
   redirect="로그인 성공 시 role에 따라 /dashboard 또는 /admin", legacy_alias="없음",
   e2e_coverage="tests/e2e/specs/01-login.spec.ts(2 tests, phase0 compose 필요·현재 미가동 추정) + specs-mongle의 loginAsFirstPlayer 헬퍼가 매 테스트에서 경유",
   approved_screen_mapping="A1(로그인/프로필선택), A1-S1은 미대응 후보(현재는 select→pin 2단계, ID/PW 폼 경로는 AdminLoginView만 존재)",
   current_screenshot_evidence="없음(이번 Task는 스크린샷 촬영 대상 아님, NOT_VERIFIED)", implementation_confidence="HIGH(라우트 자체는 코드로 직접 확인)"),
 dict(route="/dashboard", route_definition='App.tsx line 66-73: ProtectedRoute > MongleAppShell > UserDashboard', page_component="pages/UserDashboard/index.tsx",
   layout_shell="MongleAppShell(단, isLegacyDashboard=true일 때 mobileNav 숨김+legacyMain 클래스 — UserDashboard가 자체 BottomNav를 갖고 있어 이중 네비 방지)",
   auth_requirement="ProtectedRoute(isLoggedIn)", family_context_requirement="Shell 헤더의 FamilySwitcher/상태안내만 관여, 페이지 자체 로직은 FamilyContext 비의존(레거시)",
   service_subscription_requirement="없음(레거시 경로라 서비스 구독 게이트 없음)", data_source="실제 백엔드 API(레거시 마크포인트 API 세트, dashboardApi.ts 추정 — 코드 미상세열람, NOT_VERIFIED)",
   loading_empty_error="NOT_VERIFIED(UserDashboard 내부 상세 미열람)", redirect="비로그인 시 / 로 Navigate",
   legacy_alias="이 경로 자체가 'legacy' 취급(코드 주석 isLegacyDashboard)", e2e_coverage="specs/02-mission.spec.ts, specs-mongle/01-shell.spec.ts(Family switch 테스트가 이 경로 위에서 수행)",
   approved_screen_mapping="A3(포인트 잔치)와 명칭·기능 일치, 시각 구조는 레거시 자체 CSS Module(재구성 후보)",
   current_screenshot_evidence="없음(NOT_VERIFIED)", implementation_confidence="HIGH(라우트+가드 확인), MEDIUM(내부 상세는 미열람)"),
 dict(route="/admin/*", route_definition='App.tsx line 76-83: AdminProtectedRoute > MongleAppShell > AdminDashboard(내부 라우팅은 AdminDashboard/index.tsx)',
   page_component="pages/AdminDashboard/index.tsx (+ views/PointView 등 내부 라우팅)", layout_shell="MongleAppShell",
   auth_requirement="AdminProtectedRoute(isLoggedIn && isAdmin)", family_context_requirement="Shell 헤더만 관여(레거시 내부 로직 비의존 추정)",
   service_subscription_requirement="없음(레거시)", data_source="실제 백엔드 admin API 세트(adminApi.ts 추정, NOT_VERIFIED 상세)",
   loading_empty_error="NOT_VERIFIED(상세 미열람)", redirect="비로그인/비관리자 시 / 로 Navigate",
   legacy_alias="레거시 취급(마크포인트/AdminDashboard 전체)", e2e_coverage="specs/03-admin.spec.ts(3 tests)",
   approved_screen_mapping="A5(관리자 포인트 관리)는 views/PointView.tsx와 명칭 일치, 시각 구조는 레거시 CSS Module",
   current_screenshot_evidence="없음(NOT_VERIFIED)", implementation_confidence="HIGH(라우트+가드), MEDIUM(내부 상세 미열람)"),
 dict(route="/wagle", route_definition='App.tsx line 86-89: ProtectedRoute > MongleAppShell > DoranLanding (canonical, post MONGLE-FE-ROUTE-NAMESPACE-MIGRATION-001)',
   page_component="platform/pages/DoranLanding.tsx", layout_shell="MongleAppShell(모바일 대화중 상태에서는 상단바 시각적으로 숨김, route+인증 로직 불변)",
   auth_requirement="ProtectedRoute(isLoggedIn)", family_context_requirement="useFamilyContextStore로 activeFamily의 doran 서비스 status 확인 — status!=='active'면 pageState='disabled'",
   service_subscription_requirement="family.services에서 service_code==='doran' 구독 상태 확인(§ MONGLE naming: doran = 기술 도메인, 노출명 와글와글)",
   data_source="**FIXTURE ONLY** — platform/doran/preview/*.ts (rooms, messages, serviceEvents 전부 하드코드 고정 데이터, 실제 백엔드 API 연결 없음). 코드 자체 주석: 'UX Gate 미리보기 · 실제 API 연결 전 화면입니다'(import.meta.env.DEV 조건부 표시)",
   loading_empty_error="4개 pageState 명시적 처리: disabled/loading/empty/error(EmptyState/LoadingState/ErrorState 컴포넌트, 그러나 loading/empty/error는 실제로 URL 쿼리 previewState로만 트리거되는 미리보기 상태 — 실 데이터 부재로 실제 도달 불가, NOT_VERIFIED 실사용 경로)",
   redirect="없음", legacy_alias="/naran/doran → /wagle (LegacyRouteRedirect, replace, query/hash 보존)",
   e2e_coverage="specs-mongle/01-shell.spec.ts 다수(honest unavailable entry, responsive nav landmark, canonical route render/refresh, legacy redirect, Back-loop 등 8+ 테스트)",
   approved_screen_mapping="A4(가족 대화)와 대응하나 승인자료는 단일 GROUP 룸 진입 상태만 존재 — 현재 구현은 Room List + GROUP/DIRECT/SERVICE 3종 kind를 이미 fixture로 지원(APPROVED_SOURCE_GAP: 승인자료가 현재 구현 범위를 못 따라감)",
   current_screenshot_evidence="없음(NOT_VERIFIED)", implementation_confidence="HIGH(라우트+가드+fixture 여부 코드로 직접 확인)"),
 dict(route="/family", route_definition='App.tsx line 90-93: ProtectedRoute > MongleAppShell > AccessBoundary(permission="family.read") > FamilyLanding',
   page_component="platform/pages/FamilyLanding.tsx", layout_shell="MongleAppShell",
   auth_requirement="ProtectedRoute(isLoggedIn) + AccessBoundary(activeFamily 존재 + family.read 권한)",
   family_context_requirement="필수(AccessBoundary가 activeFamilyId===null이면 '가족을 선택해주세요' 표시, permission 없으면 '권한이 없어요')",
   service_subscription_requirement="없음(family.read는 서비스 구독이 아니라 family 권한)", data_source="useFamilyContextStore의 context.families(실제 account-context API 기반, fixture 아님)",
   loading_empty_error="AccessBoundary가 loading/idle/no-family/no-permission 3단계 처리, FamilyLanding 자체는 family 존재 시 이름+관계만 표시하는 스텁(가족 구성원 관리 등 실제 기능 없음 — 코드 주석: '다음 단계에서 제공')",
   redirect="없음(가드 실패 시 같은 경로에서 안내 문구만 표시, Navigate 없음)", legacy_alias="/naran/family → /family",
   e2e_coverage="specs-mongle/01-shell.spec.ts(권한 없는 사용자의 '권한이 없어요' 확인, canonical route render/refresh, legacy redirect, storage migration 다수)",
   approved_screen_mapping="A2(가족 홈)에 대응할 것으로 기대되나 **현재 /family는 A2의 GreetingHeader/PromoCard/ActivityCard/ServiceGrid/Dock 중 어느 것도 구현하지 않은 순수 텍스트 스텁** — MAJOR GAP(MISSING)",
   current_screenshot_evidence="없음(NOT_VERIFIED)", implementation_confidence="HIGH(코드 직접 확인, 스텁임이 명백)"),
 dict(route="/naran/doran", route_definition='App.tsx line 100: <Route path="/naran/doran" element={<LegacyRouteRedirect to="/wagle"/>}/>',
   page_component="LegacyRouteRedirect(App.tsx 내부 컴포넌트, 페이지 아님)", layout_shell="N/A(즉시 리다이렉트)",
   auth_requirement="자체 가드 없음(리다이렉트 후 /wagle의 ProtectedRoute가 적용)", family_context_requirement="N/A",
   service_subscription_requirement="N/A", data_source="N/A", loading_empty_error="N/A",
   redirect="/wagle로 replace 리다이렉트(query/hash 보존, 단일 hop)", legacy_alias="이 경로 자체가 legacy alias",
   e2e_coverage="specs-mongle/01-shell.spec.ts: 'legacy /naran/doran and /naran/family redirect once...', 'legacy routes do not fall through to the 404 catch-all'",
   approved_screen_mapping="N/A(라우팅 인프라, 화면 아님)", current_screenshot_evidence="N/A", implementation_confidence="HIGH"),
 dict(route="/naran/family", route_definition='App.tsx line 101: <Route path="/naran/family" element={<LegacyRouteRedirect to="/family"/>}/>',
   page_component="LegacyRouteRedirect", layout_shell="N/A", auth_requirement="자체 가드 없음", family_context_requirement="N/A",
   service_subscription_requirement="N/A", data_source="N/A", loading_empty_error="N/A",
   redirect="/family로 replace 리다이렉트(query/hash 보존)", legacy_alias="이 경로 자체가 legacy alias",
   e2e_coverage="동일(01-shell.spec.ts)", approved_screen_mapping="N/A", current_screenshot_evidence="N/A", implementation_confidence="HIGH"),
 dict(route="* (404 catch-all)", route_definition='App.tsx line 106: <Route path="*" element={<NotFoundPage/>}/>',
   page_component="App.tsx 내부 NotFoundPage 함수", layout_shell="없음(page 클래스만)", auth_requirement="없음",
   family_context_requirement="없음", service_subscription_requirement="없음", data_source="없음(정적 문구)",
   loading_empty_error="N/A", redirect="'몽글로 돌아가기' 링크(/)", legacy_alias="없음(catch-all 자체가 legacy 경로에 우선순위 밀림 — React Router가 구체적 경로를 먼저 매칭하므로 /naran/* 는 절대 여기 안 걸림, 코드로 확인)",
   e2e_coverage="specs-mongle/01-shell.spec.ts: 'shows a safe not-found page...'", approved_screen_mapping="승인자료에 대응 화면 없음(N/A)",
   current_screenshot_evidence="없음", implementation_confidence="HIGH"),
]

fieldnames = ["route","route_definition","page_component","layout_shell","auth_requirement","family_context_requirement",
  "service_subscription_requirement","data_source","loading_empty_error","redirect","legacy_alias","e2e_coverage",
  "approved_screen_mapping","current_screenshot_evidence","implementation_confidence"]
with open(OUT, "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=fieldnames)
    w.writeheader()
    for r in rows: w.writerow(r)
print(f"wrote {len(rows)} rows")
