#!/usr/bin/env python3
import csv

OUT = "/tmp/mongle-wave6-0ab/6.0A/approved_screen_inventory.csv"

rows = [
 dict(screen_id="A1", source_file="standalone-src.html", source_fragment='id="1a"', viewport="480x920 (mockup canvas, not a real device size)",
   page_title="로그인 / 프로필 선택", route_estimated="NOT_VERIFIED (no route encoded in static mockup)",
   visible_zones="StatusBarMock; BrandHero(logo+title+subtitle); ProfileSelectorCard(list of 3 PlayerCard); AdminEntryRow; HomeIndicatorBar",
   primary_cta="프로필 카드 선택(›)", navigation="없음(단일 화면)", header="가짜 iOS 상태바(9:41/신호/배터리)",
   footer_dock="없음(Dock 아님, 관리자 로그인 링크 행)", modal_dialog="없음",
   loading_empty_error="지호 카드=잠김 상태(5회 실패, 5분 후 재시도) 예시만 존재. loading/empty 상태 이미지 없음",
   responsive_variant="단일 480px 목업만 존재, 반응형 변형 없음", approval_confidence="HIGH(PNG 근거 있음: screen_login_approved.png)",
   missing_state="세로 태블릿/데스크톱 변형 없음", source_conflict="see TIER1_HTML_VISUAL_DELTA A1: aspect ratio delta",
   pm_decision_required="로고 히어로 확대 비율(HTML 210px vs PNG 비율상 더 큼)"),
 dict(screen_id="A1-S1", source_file="standalone-src.html", source_fragment='id="1a-1"', viewport="480x921 (mockup canvas)",
   page_title="순수 로그인 (아이디 / 비밀번호)", route_estimated="NOT_VERIFIED",
   visible_zones="StatusBarMock; BrandHero(작은 로고 150px); LoginForm(아이디 입력, 비밀번호 입력+에러, 로그인상태유지 체크, 로그인 버튼, 구분선, 프로필선택으로 돌아가기, 안내 배너); FooterRow(버전+관리자로그인)",
   primary_cta="로그인 버튼(단색 pill)", navigation="프로필 선택으로 돌아가기 버튼",
   header="가짜 iOS 상태바", footer_dock="버전 표시 + 관리자 로그인 링크",
   loading_empty_error="비밀번호 오류 상태 1건 예시(2/5 실패 카운터) 존재. 성공/로딩 상태 없음",
   responsive_variant="단일 480px 목업만 존재", approval_confidence="MEDIUM(전용 approved PNG 없음, screen_login_approved.png는 A1과 공유 추정)",
   missing_state="전용 PNG 없음(SOURCE_MISSING)", source_conflict="없음(PNG 자체가 없어 비교 불가)",
   pm_decision_required="이 ID/PW 로그인 폼이 현재 player-select+PIN 플로우와 별도 경로로 유지되는지, 아니면 관리자 로그인(AdminLoginView)과 통합되는지"),
 dict(screen_id="A2", source_file="standalone-src.html", source_fragment='id="1b"', viewport="480x806 (mockup canvas)",
   page_title="가족 홈", route_estimated="NOT_VERIFIED(추정 성격: '/', '/family', 또는 신규 홈. 승인자료에 문자열 route 없음)",
   visible_zones="StatusBarMock; GreetingHeader(avatar+인사말+알림벨); ChatPromoHeroCard(그라디언트, 로고워터마크, 말풍선점, CTA); RecentActivityCard(3행 타임라인); ServiceGrid(2x2: 포인트잔치/가족일정(준비중)/앨범(준비중)/할일(준비중)); BottomDock(4탭: 홈/포인트잔치/대화/나); HomeIndicatorBar",
   primary_cta="가족 대화 히어로 카드 '바로가기'", navigation="BottomDock 4탭(홈/포인트잔치/대화/나)",
   header="인사말 헤더(아바타+이름+알림)", footer_dock="4탭 BottomDock, 활성탭=홈(보라색)",
   modal_dialog="없음", loading_empty_error="상태 변형 없음(항상 데이터 있는 happy-path만)",
   responsive_variant="단일 480px 목업만 존재", approval_confidence="HIGH(PNG 근거: screen_family_home_approved.png)",
   missing_state="loading/empty 홈 상태 없음; 데스크톱 홈 레이아웃 없음", source_conflict="TIER1 delta 참조(아바타/그라디언트 톤)",
   pm_decision_required="ServiceGrid 4개 중 3개 '준비중' 배지 항목(가족일정/앨범/할일)의 실제 구현 순서 및 BottomDock에 없는 이유"),
 dict(screen_id="A3", source_file="standalone-src.html", source_fragment='id="1c"', viewport="480x1005 (mockup canvas)",
   page_title="포인트 잔치", route_estimated="NOT_VERIFIED(추정: /dashboard 계열, 현재 legacy UserDashboard와 명칭 일치)",
   visible_zones="StatusBarMock; PageHeader(로고+타이틀+로그아웃pill); ProfileSummaryCard(아바타+레벨+진행바+3분할 통계); WeekDateStrip(7일 캘린더); FamilyCheerCard(2개 응원 메시지); TodayMissionListCard(4개 미션 행: 완료/진행중/승인대기/사용내역); BottomDock",
   primary_cta="미션 행의 '바로가기'", navigation="BottomDock(활성=포인트잔치)",
   header="로고+타이틀+로그아웃", footer_dock="4탭 BottomDock",
   modal_dialog="없음", loading_empty_error="미션 상태 4종(완료/진행중 3-5/승인대기 0-1/차감내역) happy-path 예시만. empty/error 없음",
   responsive_variant="단일 480px", approval_confidence="HIGH(PNG: screen_point_festival_approved.png)",
   missing_state="레벨업 애니메이션, 빈 미션 리스트 상태 없음", source_conflict="TIER1 delta 참조",
   pm_decision_required="현재 UserDashboard(레거시)와 이 승인 화면의 시각적 재구성 범위(레벨/미션/응원 로직은 MUST_PRESERVE, 시각은 재구성 후보)"),
 dict(screen_id="A4", source_file="standalone-src.html", source_fragment='id="1d"', viewport="480x935 (mockup canvas)",
   page_title="가족 대화(GROUP 단일 룸)", route_estimated="NOT_VERIFIED(현재 canonical: /wagle)",
   visible_zones="StatusBarMock; ChatHeader(뒤로가기+룸명+참여인원+아바타스택+로고); MessageTimeline(날짜구분선, 수신/발신 말풍선, unread구분선, 앨범공유 시스템카드, 사진첨부 3장 썸네일); Composer(첨부+카메라+입력+전송원형버튼); BottomDock",
   primary_cta="Composer 전송 버튼", navigation="뒤로가기(←), BottomDock(활성=대화)",
   header="ChatHeader(룸명+참여자)", footer_dock="4탭 BottomDock + 그 위 Composer",
   modal_dialog="없음", loading_empty_error="'여기부터 안 읽음' 구분선 예시 1건. Room List 자체가 없음(단일 룸 진입 상태만 존재)",
   responsive_variant="단일 480px, 데스크톱/Room List 변형 없음(SOURCE_MISSING)",
   approval_confidence="HIGH(PNG: screen_family_chat_approved.png)",
   missing_state="Room List 화면, DIRECT/SERVICE 룸 승인 화면 없음(APPROVED_SOURCE_GAP)",
   source_conflict="TIER1 delta 참조",
   pm_decision_required="승인자료에 없는 Room List·DIRECT·SERVICE 화면을 현재 구현(fixture 3-kind 지원)이 어느 범위까지 승인 근거로 확장 적용할지"),
 dict(screen_id="A5", source_file="standalone-src.html", source_fragment='id="1e"', viewport="1440x1030 (데스크톱 전용 목업)",
   page_title="관리자 · 포인트 관리", route_estimated="NOT_VERIFIED(현재 canonical: /admin/points)",
   visible_zones="AdminSidebar(로고+가족명+6항목 nav+계정푸터); MainHeader(타이틀+날짜필터+차감추가버튼); PlayerFilterTabs(전체/서연/민준); StatCardRow(3장: 서연보유/민준보유/오늘총차감); DeductionDataTable(6열 헤더+5행+페이지네이션); InfoBanner",
   primary_cta="＋차감 추가 버튼", navigation="AdminSidebar 6항목(포인트관리 활성)",
   header="AdminSidebar+MainHeader", footer_dock="없음(데스크톱 사이드바 구조)",
   modal_dialog="행 편집(✎)/삭제(🗑) 아이콘만 존재, 다이얼로그 자체 이미지 없음(SOURCE_MISSING)",
   loading_empty_error="happy-path 5행 예시만. loading/empty/error 상태 없음",
   responsive_variant="데스크톱 1440px 전용, 모바일 admin 변형 없음(SOURCE_MISSING)",
   approval_confidence="HIGH(PNG: screen_admin_point_approved.png, 최고 일치도)",
   missing_state="차감 추가/편집 모달 화면 없음; 미션관리/사용자관리/알림관리/설정 등 나머지 5개 사이드바 화면 없음(APPROVED_SOURCE_GAP)",
   source_conflict="TIER1 delta 참조(가장 낮은 delta)",
   pm_decision_required="사이드바 6항목 중 5개(대시보드/미션관리/사용자관리/알림관리/설정) 승인 화면 부재를 어떻게 처리할지"),
 dict(screen_id="EXTRA-01", source_file="standalone-src.html", source_fragment='id="1f"', viewport="480x951",
   page_title="나 · 프로필", route_estimated="NOT_VERIFIED", visible_zones="ProfileHeaderCard; LevelProgressCard; ActivityListCard(3행); SettingsListCard(3행: 알림설정 토글/PIN변경/가족구성원); LogoutButton; BottomDock(활성=나)",
   primary_cta="프로필 수정 pill", navigation="BottomDock(활성=나)", header="타이틀 '나' + 설정/알림 아이콘",
   footer_dock="4탭 BottomDock", modal_dialog="없음", loading_empty_error="happy-path만",
   responsive_variant="단일 480px", approval_confidence="LOW(전용 approved PNG 없음, SOURCE_MISSING)",
   missing_state="전용 PNG 없음", source_conflict="없음(비교 불가)",
   pm_decision_required="A1~A5 범위 밖 화면이므로 이번 Wave 구현 우선순위에 포함할지"),
 dict(screen_id="EXTRA-02", source_file="standalone-src.html", source_fragment='id="1g"', viewport="480x980",
   page_title="가족 일정(준비중 서비스 상세 목업)", route_estimated="NOT_VERIFIED",
   visible_zones="NOT_FULLY_READ(시간 예산상 표제/구조만 확인, 세부 zone 미세 분해는 生략 — see 주의사항)",
   primary_cta="NOT_VERIFIED", navigation="BottomDock 추정", header="StatusBarMock 확인됨",
   footer_dock="NOT_VERIFIED", modal_dialog="NOT_VERIFIED", loading_empty_error="NOT_VERIFIED",
   responsive_variant="단일 480px", approval_confidence="LOW(SOURCE_MISSING: 전용 PNG 없음)",
   missing_state="세부 zone 분해 NOT_VERIFIED(effort 배분상 A1~A5 우선, EXTRA는 표제 수준만 확인)",
   source_conflict="없음", pm_decision_required="EXTRA 화면 4종(1f~1i)에 대한 세밀 실측이 이번 Wave에 필요한지, 필요 시 후속 Task로 분리할지"),
 dict(screen_id="EXTRA-03", source_file="standalone-src.html", source_fragment='id="1h"', viewport="480x1296",
   page_title="앨범(준비중 서비스 상세 목업)", route_estimated="NOT_VERIFIED",
   visible_zones="NOT_FULLY_READ(표제만 확인)", primary_cta="NOT_VERIFIED", navigation="BottomDock 추정",
   header="StatusBarMock 확인됨", footer_dock="NOT_VERIFIED", modal_dialog="NOT_VERIFIED",
   loading_empty_error="NOT_VERIFIED", responsive_variant="단일 480px",
   approval_confidence="LOW(SOURCE_MISSING: 전용 PNG 없음)", missing_state="세부 zone 분해 NOT_VERIFIED",
   source_conflict="없음", pm_decision_required="EXTRA-02와 동일"),
 dict(screen_id="EXTRA-04", source_file="standalone-src.html", source_fragment='id="1i"', viewport="480x975",
   page_title="할 일(준비중 서비스 상세 목업)", route_estimated="NOT_VERIFIED",
   visible_zones="NOT_FULLY_READ(표제만 확인, BottomDock 확인됨: 활성=홈으로 표시되어 있어 실제로는 독립 탭이 아닌 홈에서 진입하는 화면으로 추정)",
   primary_cta="NOT_VERIFIED", navigation="BottomDock(활성=홈으로 렌더됨 — 이 자체가 흥미로운 구조적 단서)",
   header="StatusBarMock 확인됨", footer_dock="4탭 BottomDock 확인(활성=홈)", modal_dialog="NOT_VERIFIED",
   loading_empty_error="NOT_VERIFIED", responsive_variant="단일 480px",
   approval_confidence="LOW(SOURCE_MISSING: 전용 PNG 없음)", missing_state="세부 zone 분해 NOT_VERIFIED",
   source_conflict="없음", pm_decision_required="EXTRA-02와 동일"),
]

fieldnames = ["screen_id","source_file","source_fragment","viewport","page_title","route_estimated",
  "visible_zones","primary_cta","navigation","header","footer_dock","modal_dialog",
  "loading_empty_error","responsive_variant","approval_confidence","missing_state",
  "source_conflict","pm_decision_required"]

with open(OUT, "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=fieldnames)
    w.writeheader()
    for r in rows:
        w.writerow(r)
print(f"wrote {len(rows)} rows")
