"""Wave 5 fresh Markpoint Mission/Ledger target schema; no legacy backfill."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision="0010_markpoint_target_ledger"
down_revision="0009_wagle_realtime_push_pin"
branch_labels=None
depends_on=None

def _member_fk(name, column):
    return sa.ForeignKeyConstraint([column,"family_group_id"],["family_memberships.id","family_memberships.family_group_id"],name=name,ondelete="RESTRICT")

def upgrade():
    op.create_table("markpoint_mission_templates",sa.Column("id",sa.BigInteger,primary_key=True),sa.Column("family_group_id",sa.Integer,sa.ForeignKey("family_groups.id",ondelete="RESTRICT"),nullable=False),sa.Column("assignee_membership_id",sa.Integer,nullable=False),sa.Column("created_by_membership_id",sa.Integer,nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("reward_amount",sa.Integer,nullable=False),sa.Column("cycle_type",sa.String(20),server_default="weekly",nullable=False),sa.Column("start_date",sa.Date,nullable=False),sa.Column("end_date",sa.Date),sa.Column("day_of_week",sa.Integer),sa.Column("status",sa.String(20),server_default="active",nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.CheckConstraint("reward_amount >= 0",name="ck_markpoint_template_reward_nonnegative"),sa.CheckConstraint("day_of_week IS NULL OR day_of_week BETWEEN 0 AND 6",name="ck_markpoint_template_day"),sa.CheckConstraint("status IN ('active', 'cancelled')",name="ck_markpoint_template_status"),sa.CheckConstraint("cycle_type IN ('daily', 'weekly', 'biweekly', 'monthly', 'quarterly', 'yearly')",name="ck_markpoint_template_cycle"),sa.CheckConstraint("end_date IS NULL OR end_date >= start_date",name="ck_markpoint_template_date_range"),_member_fk("fk_markpoint_template_assignee_family","assignee_membership_id"),_member_fk("fk_markpoint_template_creator_family","created_by_membership_id"))
    op.create_table("markpoint_missions",sa.Column("id",sa.BigInteger,primary_key=True),sa.Column("family_group_id",sa.Integer,sa.ForeignKey("family_groups.id",ondelete="RESTRICT"),nullable=False),sa.Column("assignee_membership_id",sa.Integer,nullable=False),sa.Column("created_by_membership_id",sa.Integer,nullable=False),sa.Column("approved_by_membership_id",sa.Integer),sa.Column("template_id",sa.BigInteger,sa.ForeignKey("markpoint_mission_templates.id",ondelete="RESTRICT")),sa.Column("scheduled_for",sa.Date,nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("reward_amount",sa.Integer,nullable=False),sa.Column("status",sa.String(24),server_default="active",nullable=False),sa.Column("rejection_reason",sa.Text),sa.Column("submitted_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("cancelled_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.CheckConstraint("reward_amount >= 0",name="ck_markpoint_mission_reward_nonnegative"),sa.CheckConstraint("status IN ('active', 'pending_approval', 'completed', 'rejected', 'cancelled', 'expired')",name="ck_markpoint_mission_status"),sa.UniqueConstraint("template_id","scheduled_for",name="uq_markpoint_mission_template_date"),_member_fk("fk_markpoint_mission_assignee_family","assignee_membership_id"),_member_fk("fk_markpoint_mission_creator_family","created_by_membership_id"),_member_fk("fk_markpoint_mission_approver_family","approved_by_membership_id"))
    op.create_table("markpoint_ledger_entries",sa.Column("id",sa.BigInteger,primary_key=True),sa.Column("family_group_id",sa.Integer,sa.ForeignKey("family_groups.id",ondelete="RESTRICT"),nullable=False),sa.Column("family_membership_id",sa.Integer,nullable=False),sa.Column("amount",sa.Integer,nullable=False),sa.Column("entry_type",sa.String(32),nullable=False),sa.Column("source_type",sa.String(40),nullable=False),sa.Column("source_identifier",sa.String(128),nullable=False),sa.Column("idempotency_key",sa.String(160),nullable=False),sa.Column("reversal_of_entry_id",sa.BigInteger,sa.ForeignKey("markpoint_ledger_entries.id",ondelete="RESTRICT")),sa.Column("created_by_membership_id",sa.Integer),sa.Column("reason",sa.String(300)),sa.Column("metadata",postgresql.JSONB,server_default=sa.text("'{}'::jsonb"),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.CheckConstraint("amount <> 0",name="ck_markpoint_ledger_amount_nonzero"),sa.CheckConstraint("entry_type IN ('MISSION_REWARD', 'MANUAL_CREDIT', 'MANUAL_DEBIT', 'REVERSAL', 'CORRECTION')",name="ck_markpoint_ledger_entry_type"),sa.UniqueConstraint("family_group_id","idempotency_key",name="uq_markpoint_ledger_family_idempotency"),sa.UniqueConstraint("reversal_of_entry_id",name="uq_markpoint_ledger_one_reversal"),_member_fk("fk_markpoint_ledger_member_family","family_membership_id"),_member_fk("fk_markpoint_ledger_actor_family","created_by_membership_id"))
    op.create_table("markpoint_balance_projections",sa.Column("id",sa.BigInteger,primary_key=True),sa.Column("family_group_id",sa.Integer,sa.ForeignKey("family_groups.id",ondelete="RESTRICT"),nullable=False),sa.Column("family_membership_id",sa.Integer,nullable=False),sa.Column("current_balance",sa.Integer,server_default="0",nullable=False),sa.Column("lifetime_earned",sa.Integer,server_default="0",nullable=False),sa.Column("lifetime_spent",sa.Integer,server_default="0",nullable=False),sa.Column("version",sa.Integer,server_default="0",nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.UniqueConstraint("family_group_id","family_membership_id",name="uq_markpoint_balance_family_member"),sa.CheckConstraint("lifetime_earned >= 0 AND lifetime_spent >= 0 AND version >= 0",name="ck_markpoint_balance_nonnegative"),_member_fk("fk_markpoint_balance_member_family","family_membership_id"))
    op.create_table("markpoint_audit_events",sa.Column("id",sa.BigInteger,primary_key=True),sa.Column("family_group_id",sa.Integer,sa.ForeignKey("family_groups.id",ondelete="RESTRICT"),nullable=False),sa.Column("actor_membership_id",sa.Integer),sa.Column("action",sa.String(60),nullable=False),sa.Column("aggregate_type",sa.String(50),nullable=False),sa.Column("aggregate_id",sa.String(64),nullable=False),sa.Column("payload",postgresql.JSONB,server_default=sa.text("'{}'::jsonb"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False))
    op.execute("CREATE FUNCTION markpoint_ledger_immutable() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'markpoint ledger is append-only'; END; $$ LANGUAGE plpgsql")
    op.execute("CREATE TRIGGER markpoint_ledger_no_update BEFORE UPDATE ON markpoint_ledger_entries FOR EACH ROW EXECUTE FUNCTION markpoint_ledger_immutable()")
    op.execute("CREATE TRIGGER markpoint_ledger_no_delete BEFORE DELETE ON markpoint_ledger_entries FOR EACH ROW EXECUTE FUNCTION markpoint_ledger_immutable()")

def downgrade():
    op.execute("DROP TRIGGER markpoint_ledger_no_delete ON markpoint_ledger_entries")
    op.execute("DROP TRIGGER markpoint_ledger_no_update ON markpoint_ledger_entries")
    op.execute("DROP FUNCTION markpoint_ledger_immutable()")
    op.drop_table("markpoint_audit_events"); op.drop_table("markpoint_balance_projections"); op.drop_table("markpoint_ledger_entries"); op.drop_table("markpoint_missions"); op.drop_table("markpoint_mission_templates")
